- 김민재/week1/2023.02.27/boj1085/README.md
- 김민재/week1/2023.02.27/boj1085/boj1085.py
- 김민재/week1/2023.02.27/boj1259/README.md
- 김민재/week1/2023.02.27/boj1259/boj1259.py
close #35 
일일 목표 달성
Python3.8에서 새로 생긴 := 연산자를 드디어 사용해봤는데, 굉장히 편하고 가독성도 상당히 높아진 듯 하다.
앞으로도 자주 사용할듯 👍
> [python] #35 solve boj1085, boj1259 (2023-02-28)

- 서동현/week1/2023.03.01/boj 2583/README.md
- 서동현/week1/2023.03.01/boj 2583/boj 2583.cpp
- 서동현/week1/2023.03.01/boj 2667/README.md
- 서동현/week1/2023.03.01/boj 2667/boj 2667.cpp
close #51 
일일목표달성
**BOJ 2583번**
**BOJ 2557번**
**BOJ 2583번**
```cpp
#define X first
#define Y second
int board[102][102];
bool vis[102][102];
int n,m,k;
int dx[4] = {1, 0, -1, 0};
int dy[4] = {0, 1, 0, -1};
int arr[102];
int idx = 0;
int main (void)
{
ios_base::sync_with_stdio(0);
cin.tie(0);
cin >> n >> m >> k;
while(k--)
{
int x,y,x2,y2;
cin >> x >> y >> x2 >> y2;
for (int i = y; i < y2; i++)
{
for (int j = x; j < x2; j++)
{
board[i][j] = 1;
}
}
}
int cnt = 0;
for (int i = 0; i < n; i++)
{
for (int j = 0; j < m; j++)
{
if (board[i][j] == 0 && vis[i][j] == 0)
{
cnt++;
int sum = 1;
vis[i][j] = 1;
queue<pair<int, int>> Q;
Q.push({i,j});
while (!Q.empty())
{
pair<int, int> cur = Q.front();
Q.pop();
for (int dir = 0; dir < 4; dir++)
{
int nx = …
```
> [c++] #51 boj 2583, boj 2667

- 김형훈/week1/2023.03.01/boj21608/README.md
- 김형훈/week1/2023.03.01/boj21608/boj21608.cpp
close #53
일일 목표 달성
```cpp
int N;
int cnt_2[22][22];
int board[22][22];
struct info
{
public:
pair<int,int> pos;
int satis;
bool wanted[402];
vector<pair<int,int>> near;	
};
info students[402];
int main()
{
ios::sync_with_stdio(0);
cin.tie(0);
cin >> N;
for (int i=0; i<N; i++)
{
cnt_2[0][i]++;
cnt_2[N-1][i]++;
cnt_2[i][0]++;
cnt_2[i][N-1]++;
}
for (int i=0; i<N*N; i++)
{
int cur, prefer;
cin >> cur;
int cnt_1[22][22] = {0};
for (int j=0; j<4; j++)
{
cin >> prefer;
students[cur].wanted[prefer] = true;
for (auto e:students[prefer].near)
{
auto [x,y] = e;
cnt_1[x][y]++;
}
}
int tmp_1 = 0, tmp_2 = 5;
for (int i=0; i<N; i++)
for (int j=0; j<N; j++)
{
if (board[i][j])
continue ;
if (cnt_1[i][j] > tmp_1)
{
students[cur].pos = {i,j};
tmp_1 = …
```
> [c++] #53 solve boj21608

- 김민재/week1/2023.03.01/boj1018/README.md
- 김민재/week1/2023.03.01/boj1018/boj1018.py
- 김민재/week1/2023.03.01/boj1436/README.md
- 김민재/week1/2023.03.01/boj1436/boj1436.py
close #52
일일 목표 달성
```python
import sys
M, N = map(int, sys.stdin.readline().split())
board = [sys.stdin.readline().rstrip() for m in range(M)]
color_check = [[0 for n in range(N)] for m in range(M)]
for m in range(M):
for n in range(N):
color_check[m][n] += ('W' if (m + n) % 2 == 0 else 'B') != board[m][n]
result = []
for m in range(M - 7):
for n in range(N - 7):
x = sum(sum(color_check[i][n:n + 8]) for i in range(m, m + 8))
result.append(min(x, 64 - x))
sys.stdout.write(str(min(result)))
```
```python
import sys
N = int(sys.stdin.readline())
count = 0
for i in range(N):
if i % 1000 == 666:
for j in range(1000):
count += 1
if count == N:
sys.stdout.write(str(i * 1000 + j))
exit()
elif i % 100 == 66:
for j in range(100):
count += 1
if count == N:
sys.stdout.write(str(i * 1000 + 600 + j)) …
```
> [python] #35 solve boj1018, boj1436 (2023-03-01)

- 이주현/week1/230301/boj10810/README.md
- 이주현/week1/230301/boj10810/boj10810.c
close #49
일일 목표(?) 달성
github 적응기간이 많이 필요할거 같네요😅
> [c] #49 백준 10810

- 임현순/Week1/boj13913/boj13913.cpp
#43 
주간목표 첫번째
[Boj 13913](https://www.acmicpc.net/problem/13913)
Github랑 빨리 친해지자..
https://www.inflearn.com/course/10%EC%A3%BC%EC%99%84%EC%84%B1-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%81%B0%EB%8F%8C
> [c++] #43 boj 13913

- 홍석민/week1/2022.03.02/boj11722/README.md
- 홍석민/week1/2022.03.02/boj11722/boj11722.py
- 홍석민/week1/2022.03.02/boj12738/README.md
- 홍석민/week1/2022.03.02/boj12738/boj12738.py
- 홍석민/week1/2022.03.02/leetcode66/66.plus-one.py
- 홍석민/week1/2022.03.02/leetcode66/README.md
- 홍석민/week1/2022.03.02/leetcode67/67.add-binary.py
- 홍석민/week1/2022.03.02/leetcode67/README.md
close #67, #69
WEEK1 2022.03.02 일일 목표 달성
Solution For
* [BOJ 11722](https://www.acmicpc.net/problem/11722)
* [BOJ 12738](https://www.acmicpc.net/problem/12738)
* [Leetcode 66](https://leetcode.com/problems/plus-one/description/)
* [Leetcode 67](https://leetcode.com/problems/add-binary/description/)
첫 PR로 백준쪽 리드미는 비록 부족하지만 이후 내용은 더 채우도록 하겠습니다.
> [python] #67 #69 solve BOJ11722 BOJ12738 Leetcode 66 Leetcode 67

- 최호준/2477.cpp
- 최호준/2792.cpp
일일 목표 달성!
* [boj 2477](https://www.acmicpc.net/problem/2477)
* [boj 2792](https://www.acmicpc.net/problem/2792)
[좌표로 다각형 넓이 구하기](https://www.mathopenref.com/coordpolygonarea2.html)
> 최호준 week-1 2023.03.01 일일 목표 달성

- 서동현/week1/2023.03.02/boj 11729/README.md
- 서동현/week1/2023.03.02/boj 11729/boj 11729.cpp
- 서동현/week1/2023.03.02/boj 1629/README.md
- 서동현/week1/2023.03.02/boj 1629/boj 1629.cpp
close #72 
일일목표달성
```cpp
// 필요한 수학적 개념
// 1.
//    7 * 7 * 7 * 7 % 5
// = (7 * 7 * 7 * 7) % 5
// = (7 % 5) * (7 % 5) * (7 % 5) * (7 % 5) % 5
// 2.
// 시간복잡도를 생각해서 재귀를 통해 b를 2로 나눠서 계산
// (2^6 = (2^3) * (2^3))
// int 오버플로우를 고려해서 long long 선언, c로 나눈 나머지만 가지고 연산
long long pow(long long a, long long b, long long c)
{
if (b == 1)
return a % c;
long long val = pow(a, b / 2, c);
val = val * val % c;
// 홀 수일 땐 a를 한 번 더 곱해준다.
if (b % 2 == 0)
return val;
return val * a % c;
}
int main()
{
ios_base::sync_with_stdio(0);
cin.tie(0);
long long a,b,c;
cin >> a >> b >> c;
cout << pow(a, b, c);
return 0;
}
```
```cpp
// a = 출발 장대, b = 도착 장대, n = 탑 갯수
// 탑이 n개일 때
// n - 1을 비어있는 장대로 빼놓고 n을 b장대로 옮긴 후 다시 n - 1을 b로 옮긴다. …
```
> [c++] #72 boj 1629 boj 11729

- 김민재/week1/2023.03.02/boj1654/README.md
- 김민재/week1/2023.03.02/boj1654/boj1654.py
- 김민재/week1/2023.03.02/boj1874/README.md
- 김민재/week1/2023.03.02/boj1874/boj1874.py
close #68 
일일 목표 달성
```python
import sys
K, N = map(int, sys.stdin.readline().split())
cables = [int(sys.stdin.readline()) for _ in range(K)]
min_cable_length = 1
max_cable_length = max(cables)
while min_cable_length <= max_cable_length:
mid_cable_length = (min_cable_length + max_cable_length) // 2
if sum(map(lambda x: x // mid_cable_length, cables)) >= N:
min_cable_length = mid_cable_length + 1
else:
max_cable_length = mid_cable_length - 1
sys.stdout.write(str(max_cable_length))
```
```python
import sys
n, *nums = map(int, sys.stdin.buffer.read().splitlines())
count = 1
stack = []
stack_operator = []
for stack_pop_num in nums:
while count <= stack_pop_num:
stack.append(count)
stack_operator.append("+")
count += 1
if stack.pop() != stack_pop_num:
stack_operator.clear()
break …
```
> [python] #68 solve boj1654, boj1874 (2023-03-02)

- 서동현/week1/2023.03.03/boj 1074/README.md
- 서동현/week1/2023.03.03/boj 1074/boj 1074.cpp
- 서동현/week1/2023.03.03/boj 2953/README.md
- 서동현/week1/2023.03.03/boj 2953/boj 2953.cpp
close #77 
일일목표달성
```cpp
int main()
{
ios_base::sync_with_stdio(0);
cin.tie(0);
int sum = 0;
int n;
for (int i = 0; i < 5; i++)
{
int a,b,c,d;
cin >> a >> b >> c >> d;
if (a + b + c + d > sum)
{
sum = a + b + c + d;
n = i + 1;
}
}
cout << n << "\n";
cout << sum;
return 0;
}
```
```cpp
/*
구역 나누기
1번			2번
0  1 |  4  5
2  3 |  6  7
-------|-------
8  9 | 12 13
10 11 | 14 15
3번			4번
ex) n = 2, r = 0, c = 2라면, half * half(1번구역 넓이 = 4) + rec_z(n - 1, r, c - half)(작은 사각형 1번 구역 = 0)
4 출력
*/
int rec_z(int n, int r, int c)
{
if(n == 0)	//base condition
return 0;
int half = 1 << (n - 1);	// 한 변의 절반 == 2^(n-1)
if (r < half && c < half)		//1번 구역
return rec_z(n-1, r, c);
else if (r < half && c >= half)		//2번 구역 …
```
> [c++] #77 boj 1074 boj2953

- 김민재/week1/2023.03.03/boj1920/README.md
- 김민재/week1/2023.03.03/boj1920/boj1920.py
- 김민재/week1/2023.03.03/boj1929/README.md
- 김민재/week1/2023.03.03/boj1929/boj1929.py
close #91 
일일 목표 달성
```python
import sys
N = sys.stdin.readline()
A = set(sys.stdin.readline().split())
M = sys.stdin.readline()
sys.stdout.write('\n'.join(('1' if num in A else '0') for num in sys.stdin.readline().split()))
```
```python
import sys
M, N = map(int, sys.stdin.readline().split())
eratosthenes = [False] + [True] * (N - 1)
for i in range(2, int(N ** 0.5) + 1):
if eratosthenes[i - 1]:
for non_prime_num in range(2, N // i + 1):
eratosthenes[i * non_prime_num - 1] = False
sys.stdout.write('\n'.join([f'{i + M}' for i, is_prime in enumerate(eratosthenes[M - 1:]) if is_prime]))
```
소수들의 리스트를 구하기 위한 방법 중 에라토스테네스의 체가 아닌 다른 방법론을 적용하려고 수학적 개념을 검색했으나, 이해가 안된다... :(
> [python] #91 solve boj1920, boj1929 (2023-03-03)

- 임현순/Week1/boj17071/boj17071.cpp
close #87 
주간 목표 두번째
[BOJ 17071](https://www.acmicpc.net/problem/17071)
문제에 도전해 봤지만 어려워서 결국 정답을 보며 코드를 이해하려고 노력했다. 완전히 익숙해질 때까지 반복해서 문제를 다시 풀어봐야겠다.
https://www.inflearn.com/course/10%EC%A3%BC%EC%99%84%EC%84%B1-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%81%B0%EB%8F%8C/dashboard
> [c++] #43 boj 17071

- 최호준/week01/230304/15724.cpp
- 최호준/week01/230304/leet_20.py
일일 목표 달성!
* [leet code 20](https://leetcode.com/problems/valid-parentheses/)
* [boj 15724](https://www.acmicpc.net/problem/15724)
주지수 문제는 prefix sum을 안다면 쉽게 풀 수 있다고 생각한다.
[같은 문제는 아니지만 비슷한 문제 해설 링크를 첨부할게요! 같은 알고리즘을 사용하는 문제입니다. 그림이 있어서 prefix sum을 이해하기 좋더라고요.](https://exponential-e.tistory.com/59)
> 최호준 week-1 2023.03.04 일일 목표 달성!

- 최호준/week02/230306/2257.cpp
일일 목표 달성!
* [boj 2256](https://www.acmicpc.net/problem/2257)
* 재귀 + 스택으로 문제를 해결했다.
> [c++] boj 2257

- 손슬기/week1/2023.03.02/boj10156/README.md
- 손슬기/week1/2023.03.02/boj10156/boj10156.py
- 손슬기/week1/2023.03.02/boj10833/README.md
- 손슬기/week1/2023.03.02/boj10833/boj10833.py
- 손슬기/week1/2023.03.02/boj10871/README.md
- 손슬기/week1/2023.03.02/boj10871/boj10871.py
- 손슬기/week1/2023.03.02/boj10872/README.md
- 손슬기/week1/2023.03.02/boj10872/boj10872.py
- 손슬기/week1/2023.03.02/boj1564/README.md
- 손슬기/week1/2023.03.02/boj1564/boj1564.py
- 손슬기/week1/2023.03.02/boj2439/README.md
- 손슬기/week1/2023.03.02/boj2439/boj2439.py
- 손슬기/week1/2023.03.02/boj2576/README.md
- 손슬기/week1/2023.03.02/boj2576/boj2576.py
close #81
일일 목표 달성
폴더명 맨 뒤에 . 을 넣는 바람에 main에 merge 되지 못하고 터지는 사태가 일어났습니다. 
싹 다 삭제하고 다시 올립니당 🥲
재리뷰 부탁해요~
> [python] #81 boj1564 boj2439 boj2576 boj10156 boj10833 boj10871 boj10872

- 손슬기/week1/2023.03.03/boj2742/README.md
- 손슬기/week1/2023.03.03/boj2742/boj2742.py
- 손슬기/week1/2023.03.03/boj2748/README.md
- 손슬기/week1/2023.03.03/boj2748/boj2848.py
- 손슬기/week1/2023.03.03/boj5522/README.md
- 손슬기/week1/2023.03.03/boj5522/boj5522.py
- 손슬기/week1/2023.03.03/boj9295/README.md
- 손슬기/week1/2023.03.03/boj9295/boj9295.py
close #83
일일 목표 달성
branch를 잘못 만들어서 close-삭제 후에 다시 업로드합니다.
재앙을 일으켜서 죄송합니당
> [python] #83 boj2742 boj2748 boj5522 boj9295

- 손슬기/week2/2023.03.05/boj11021/README.md
- 손슬기/week2/2023.03.05/boj11021/boj11021.py
- 손슬기/week2/2023.03.05/boj2839/README.md
- 손슬기/week2/2023.03.05/boj2839/boj2839.py
close #110
일일목표 달성
```
print('Case #'+str(i)+':', a+b)
대신에
print(f'Case #{i}: {a+b}') 해도 됨
이걸 string formatting - 문자열 포매팅이라고 한다.
```
https://blockdmask.tistory.com/429
> [python] #110 boj2839 boj11021

- 손슬기/week2/2023.03.06/boj25024/README.md
- 손슬기/week2/2023.03.06/boj25024/boj25024.py
- 손슬기/week2/2023.03.06/boj2743/README.md
- 손슬기/week2/2023.03.06/boj2743/boj2743.py
close #119
일일목표달성
boj2743번의 경우 파이썬에 len 함수로 간단하게 길이를 구해줄 수 있었다.
하지만 만약에 input이 '알파벳'인 경우에만 길이를 세어주게 하려면 isalpha()를 사용해서 검사할 수 있다는 걸 알았다.
boj25024번의 경우 처음에는 단순하게
```
a, b = map(int, input().split())
if a <= 12 and b <= 31:
print('Yes', 'Yes')
elif a > 12 and b <= 31:
print('No', 'Yes')
elif a <= 12 and b > 31:
print('Yes', 'No')
else:
print('No', 'No')
```
짰는데, 월별로 날짜가 31일까지인 달이 있고, 30일까지인 달이 있으니 그걸 리스트로 구분해줬다.
python에서는 if 조건을 줄 때 &&가 아닌 and를 사용할 수 있고, 
입력이 0부터 가능하다고 했으니 0보다 크고 31보다 작거나 같다를 표현할 때 0 < b <= 31 이렇게 바로 가운데에 껴도 된다는 걸 알았다.  
https://maeseok.tistory.com/51
> [python] #119 boj2743 boj25024

- 임현순/Week2/boj14497/boj14497.cpp
- 임현순/Week2/boj3197/boj3197.cpp
close #116 
주간목표 달성
[boj 14497](https://www.acmicpc.net/problem/14497)
[boj 3197](https://www.acmicpc.net/problem/3197)
복습할 겸 2문제를 다시 풀어봤는데 백조 문제는 계속 꾸준히 볼 필요가 있을 것 같다.
https://www.inflearn.com/course/10%EC%A3%BC%EC%99%84%EC%84%B1-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%81%B0%EB%8F%8C
> [c++] #116 boj14497 boj3197

- 서동현/week2/2023.03.11/boj 1992/README.md
- 서동현/week2/2023.03.11/boj 1992/boj 1992.cpp
close #140 
일일목표달성
```cpp
string board[66];
void rec(int x_start, int x_end, int y_start, int y_end)
{
if(x_start + 1 == x_end)
{
cout << board[x_start][y_start];
return;
}
int check = 1;
int sum = 0;	//전부 0일때
int max_sum = (x_end - x_start) * (y_end - y_start); // 전부 1일 때
for (int i = x_start; i < x_end; i++)
{
for (int j = y_start; j < y_end; j++)
{
sum += board[i][j] - '0';
}
}
if (sum == 0 || sum == max_sum)
{
cout << board[x_start][y_start];
return;
}
cout << '(';
int x_half = x_start + (x_end - x_start) / 2;
int y_half = y_start + (y_end - y_start) / 2;
rec(x_start, x_half, y_start, y_half);
rec(x_start, x_half, y_half, y_end);
rec(x_half, x_end, y_start, y_half);
rec(x_half, x_end, y_half, y_end);
cout << ')';
}
int main ()
{
int n;
cin …
```
> [c++] #140 boj 1992

- 최호준/week03/230312/18404.cpp
- 최호준/week03/230312/leet_83.py
일일 목표 달성!
* [boj 18404](https://www.acmicpc.net/problem/18404)
* [leet 83](https://leetcode.com/problems/remove-duplicates-from-sorted-list/)
> 최호준 week-3 2023.03.12 일일 목표 달성!

- 최호준/230307/1655.cpp
일일 목표 달성!
[boj 1655](https://www.acmicpc.net/problem/1655)
나는 한 개의 pq로 풀어서 매 삽입마다 (n/2) * log n 만큼 걸렸다. 하지만 이렇게 하면 0.1초라는 시간제한을 통과할 수 없다.
시간을 줄이는 방법이 떠오르지 않아서 [풀이를 보았다](https://gh402.tistory.com/32). 
* https://gh402.tistory.com/32
> 최호준 week-2 2023.03.07 일일 목표 달성!

- 최호준/week02/230310/1522.cpp
일일 목표 달성!
[boj 1522](https://www.acmicpc.net/problem/1522)
> 최호준 week-2 2023.03.10 일일 목표 달성!

- 서동현/week2/2023.03.08/boj1780/README.md
- 서동현/week2/2023.03.08/boj1780/boj1780.cpp
close #126 
일일목표달성
```cpp
int result[3]; //arr[0] = -1 개수, arr[1] = 0 개수, arr[2] = 1 개수
int board[2200][2200];
void rec(int x_start, int x_end, int y_start, int y_end, int num)
{
if (x_start + 1 == x_end)	//한칸짜리 종이일 때
{
if (board[x_start][y_start] == num)
result[num + 1]++;
return;
}
int check = 1;
for (int i = x_start; i < x_end; i++)
{
for (int j = y_start; j < y_end; j++)
{
if (board[i][j] != num)
check = 0;
}
}
if (check == 1)
{
result[num + 1]++;
return;
}
int x_one_third = x_start + (x_end - x_start) / 3;
int x_two_thirds = x_start + (x_end - x_start) / 3 * 2;
int y_one_third = y_start + (y_end - y_start) / 3;
int y_two_thirds = y_start + (y_end - y_start) / 3 * 2;
/*
1|2|3
-----
4|5|6
-----
7|8|9
*/
rec(x_start, x_one_third, y_start, …
```
> [c++] #126 boj 1780

- 김민재/week2/2023.03.10/boj1966/README.md
- 김민재/week2/2023.03.10/boj1966/boj1966.py
- 안현준/week3/2023.03.17/algorithm_labs/README.md
- 안현준/week3/2023.03.17/algorithm_labs/stack.c++
close #166
주간 목표 달성
```
// S.create()
// S.push()
// S.pop()
// S.top()
// S.size()
#include <iostream>
#include <stdio.h>
using namespace std; 
struct Stack
{
int	data[100];
int	len = 0; // 현재 원소 개수
int	capacity = 0; // 최대 크기
void create(int y) {
capacity = y;
}
void push(int y) {
if (len >= capacity)
printf("Stack overflow!\n");
else
data[len++] = y;
}
void pop() {
if (len <= 0)
printf("Stack underflow!\n");
else {
data[len-1] = 0;
len--;
}
}
int top() {
if (len <= 0)
return -1;
else
return data[len-1];
}
int size() {
return len;
}
};
int main()
{
Stack	s;
s.create(5);
s.push(1);
s.push(2);
s.push(3);
s.push(4);
s.push(5);
s.push(6); // overflow
s.push(7); // overflow
printf("%d\n", s.top()); // 5
s.pop();
printf("%d\n", s.top()); // 4
s.push(6);
s.push(7); // overflow
printf("%d\n", …
```
> [C/C++] #166 algo/GCgang/2023.03.17

- 김형훈/week3/2023.03.16/1459.cpp
- 김형훈/week3/2023.03.16/2212.cpp
close #172
[boj 2212 센서](https://www.acmicpc.net/problem/2212)
[boj 1459 걷기](https://www.acmicpc.net/problem/1459)
집중국의 수신 가능한 영역의 거리는 센서의 좌표 최댓값 - 최솟값으로 생각할 수 있다.  
그렇다면 거리를 최소화하기 위해서 집중국은 어디에 세워야할까?  
K가 2일때의 경우의 수이다.  
해당 그림에서 집중국의 수신 가능한 영역의 거리가 최소가 되기 위해서는 거리가 서로 가까운 센서끼리 그룹화 해서 집중국을 세우면 된다는 것을 알 수 있다.   
센서들 사이의 거리 중 N-K만큼 제일 작은 값을 선택하면 이를 구현할 수 있다.
```cpp
int N,K;
int senser[10002];
int dst[10002];
int main()
{
ios::sync_with_stdio(0);
cin.tie(0);
cin >> N >> K;
for (int i=0; i<N; i++)
cin >> senser[i];
sort(senser, senser + N);
for (int i=1; i<N; i++)
dst[i] = senser[i] - senser[i-1];
sort(dst + 1, dst + N);
int ans = 0;
for (int i=1; i<=N-K; i++)
ans += dst[i];
cout << ans;
}
``` …
> [c++] #172 solve boj2212 boj1459

- 김민재/week4/2023.03.22/boj2231/README.md
- 김민재/week4/2023.03.22/boj2231/boj2108.py
close #203
일일 목표 완료
```python
import sys
T, *inputs = map(int, sys.stdin.buffer.read().splitlines())
result = []
for k, n in zip(inputs[::2], inputs[1::2]):
floor = [population for population in range(1, n + 1)]
for i in range(k):
for j in range(1, n):
floor[j] += floor[j - 1]
result.append(floor[-1])
sys.stdout.write('\n'.join(map(str, result)))
```
해당 호수보다 낮고, 작은 모든 호에 대한 누적합을 계산하기 때문에 전형적인 DP의 메모이제이션 문제이다. k와 n의 범위가 1~14로 매우 작기 때문에 전체 계산을 해서 해당하는 호수의 값을 출력하는 방식도 괜찮을 것 같다.
> [python] #203 solve boj2231 (2023-03-22)

- 김민재/week4/2023.03.23/boj2292/README.md
- 김민재/week4/2023.03.23/boj2292/boj2798.py
close #205 
일일 목표 달성
```python
import sys
from itertools import combinations
N, M = map(int, sys.stdin.readline().split())
cards = list(map(int, sys.stdin.readline().split()))
result = 0
for selected_cards in combinations(cards, 3):
temp = sum(selected_cards)
if result < temp <= M:
result = temp
sys.stdout.write(str(result))
```
입력 범위가 크지 않아서 좀 더 가독성이 높은 코드를 위해 itertools을 사용했다. 하지만 가장 빠른 로직은 아니기 때문에, 좀 더 개선하려면 전체 배열을 정렬 한 뒤에 탐색하는것이 바람직하다.
> [python] #205 solve boj2798 (2023-03-23)

- 김형훈/week4/2023.03.25/boj1508/1508.cpp
- 김형훈/week4/2023.03.25/boj1508/README.md
close #212
일일 문제 풀이
이분 탐색
O\(logK\)
\( 1 <= K <= 50 \)
[공유기](https://www.acmicpc.net/problem/2110) 문제와 굉장히 비슷한 문제.
가장 가까운 두 심판의 거리를 a라고 할 때, a를 기준으로 심판을 최대한 많이 배치한다고 가정해보자.
a의 길이를 짧게 측정하면 배치할 수 있는 심판의 수가 많아질 것이다.  
반대로 a의 길이를 너무 길게 측정하면 배치할 수 있는 심판의 수가 적어질 것이다.  
이를 토대로 M명의 심판을 배치할 때, a의 최댓값을 구하는 코드를 구현할 수 있다.
```cpp
typedef unsigned long long ull;
// ...
int st = 0, en = arr[K-1];
ull ans = 0;
while (st <= en)
{
// 가장 가까운 거리
int mid = (st + en + 1) / 2;
int simpan = 1, tmp = 0;
// 문제에서 사전 순으로 늦는 순으로 출력하라고 했기 때문에
// 앞에서부터 탐색을 진행해서 조건에 맞는 자리를 찾아준다.
// (11110, 11101이 조건을 충족할 경우 전자가 답이다.)
ull position = 1;
// position은 배치한 자리를 저장할 변수.
// 거리를 최대한 멀게 해야 하고, 사전 순으로 가장 늦는 경우의 수를 선택해야 하므로
// 첫번째 자리는 무조건 배치하여야 해서 1부터 시작했다.
for (int i=1; i<K && simpan < M; i++)
{
int dst = arr[i] - arr[tmp];
if …
```
> [c++] #212 solve boj1508

- 임현순/Week4/prefix_sum.cpp
close #198 
알고리즘 공부하기
https://www.notion.so/Algorithm-1ae7d7d767e84183b94d45b077ba5a39?pvs=4
차근차근 꾸준히 공부하자
> [c++] #198 study algorithm

- 임현순/Week3/boj16637.cpp
close #154
[boj 16637](https://www.acmicpc.net/problem/16637)
예전에 풀었던 문제인데 다시 보니까 구현에서 어려움을 느꼈다. 꾸준한 복습의 중요성을 느꼈다.
https://www.inflearn.com/course/10%EC%A3%BC%EC%99%84%EC%84%B1-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%81%B0%EB%8F%8C
> [c++] #154 boj16637

- 김형훈/week4/2023.03.21/boj20058.cpp
close #200 
일일 문제 해결
[boj 20058 마법사 상어와 파이어스톰](https://www.acmicpc.net/problem/20058)
구현, 너비우선 탐색
O \(Q * 2의 N승 * 2의 N승\)
\( 2 ≤ N ≤ 6 \)
\( 1 ≤ Q ≤ 1,000 \)
상어 시리즈의 문제들은 전부 다 한번에 이해가 안되는것 같다.  
해당 문제에서 시계 방향으로 회전한다는 의미를 잘 해석해야 한다.  
왼쪽의 로직으로 오해할 수 있는데, 문제에서 요구하는 방식은 오른쪽이다.  
```cpp
int N, Q;
int A[70][70];
bool vis[70][70];
int dx[4] = {0,-1,0,1};
int dy[4] = {-1,0,1,0};
void my_swap(int x, int y, int len)
{
int tmp[70][70] = {0};
int n = (1<<(len + 1));
for (int i=0; i<n; i++)
for (int j=0; j<n; j++)
tmp[x + j][y + n - 1 - i] = A[x + i][y + j];
for (int i=0; i<n; i++)
for (int j=0; j<n; j++)
A[x + i][y + j] = tmp[x + i][y + j];
}
void fire(int L, int x, int y, int i)
{
if (L < 0)
return ;
// 재귀적으로 구간을 나눈 이후 시계방향으로 돌려준다.
if (L == i)
{ …
```
> [c++] #200 solve boj20058

- 최효종/week3/baek15649.cpp
- 최효종/week3/baek15649.cpp
close #169
주간 목표 달성
```c++
#include <iostream>
#include <vector>
vector<int> v;
bool visited[9];
int n, m;
void dfs() {
if (v.size() == m) 
{
for (int item : v) cout << item << ' ';
cout << '\n';
return;
}
for (int i = 1; i <= n; i++)
{
if (!visited[i]) {
v.push_back(i);
visited[i] = true;
dfs();
v.pop_back();
visited[i] = false;
}
}
}
int main() {
cin >> n >> m;
dfs();
}
```
피신 c00 8번문제와 유사한 문제인데 c++에서 사용가능한 라이브러리를 쓰니 훨씬 짧아지네요!
> [cpp] #169 boj15649

- 김민재/week7/2023.04.08/boj27866/README.md
- 김민재/week7/2023.04.08/boj27866/boj27866.py
- 김민재/week7/2023.04.08/boj2839/README.md
- 김민재/week7/2023.04.08/boj2839/boj2839.py
close #234 
일일 목표 달성
```python
import sys
sys.stdout.write(sys.stdin.readline()[int(sys.stdin.readline()) - 1])
```
```python
import sys
sugar = int(sys.stdin.readline())
if sugar % 5 == 0:
sys.stdout.write(str(sugar // 5))
else:
bags_of_5kg = sugar // 5
remaining_sugar = sugar % 5
for _ in range(3):
if remaining_sugar % 3 == 0:
bags_of_3kg = remaining_sugar // 3
sys.stdout.write(str(bags_of_5kg + bags_of_3kg))
break
remaining_sugar += 5
bags_of_5kg -= 1
if bags_of_5kg < 0:
sys.stdout.write("-1")
break
```
[BoJ 27866 분해합](https://www.acmicpc.net/problem/27866) 문제는 solved.ac의 새싹문제에 새로운 문제가 등록됐기에 한번 풀어보았다. 특이사항이 없기 때문에 따로 이야기하지는 않겠다.
[BoJ 2839 설탕 배달](https://www.acmicpc.net/problem/2839) 문제는 기본적으로 그리디 알고리즘 문제처럼 보인다. 그러나 생각을 해보면 5로 나눈 나머지가 3으로 나누어지는지 확인하기 위해서는 1이 남았을 때 +5를 해서 6으로 만들어주거나, 2가 …
> [python] #233 solve boj27866, boj2839 (2023-04-08)

- 김민재/week7/2023.04.12/boj4153/README.md
- 김민재/week7/2023.04.12/boj4153/boj4153.py
close #238 
일일 목표 달성
```python
import sys
inputs = [sorted(map(lambda y: pow(int(y), 2), x.split())) for x in sys.stdin.read().splitlines()[:-1]]
result = ["right" if sum(triangle[:2]) == triangle[2] else "wrong" for triangle in inputs]
```
이번 문제는 간단한 피타고라스 문제였기 때문에, 문제를 푸는 로직보다는 최대한 Pythonic한 코드를 짜보았다. 전처리, 연산, 출력 단계로 나눠서 배열 핸들링을 통해 결과를 도출해보았다.
> [python] #238 solve boj4153

- 김민재/week9/2023.04.24/boj10773/README.md
- 김민재/week9/2023.04.24/boj10773/boj10773.py
close #256 
일일 목표 달성
```python
import sys
inputs = map(int, sys.stdin.read().splitlines()[1:])
stack = []
for money in inputs:
if money:
stack.append(money)
else:
stack.pop()
sys.stdout.write(str(sum(stack)))
```
Class 2의 문제들은 간단한 자료구조를 다루는 문제들이 상당히 많은것 같다. 이번에도 몇일 전에 풀었던 문제와 유사한 간단한 Stack을 다루는 문제다.
> [python] #256 solve boj10773

- 김민재/week8/2023.04.21/boj10250/README.md
- 김민재/week8/2023.04.21/boj10250/boj10250.py
close #249 
일일 목표 달성
```python
import sys
testcases = [list(map(int, testcase.split())) for testcase in sys.stdin.read().splitlines()[1:]]
result = [str(((testcase[2] - 1) % testcase[0] + 1) * 100 + (testcase[2] - 1) // testcase[0] + 1) for testcase in testcases]
```
간단한 수학 계산 문제
> [python] #249 solve boj10250

- 김민재/week8/2023.04.18/boj7568/README.md
- 김민재/week8/2023.04.18/boj7568/boj7568_normal.py
- 김민재/week8/2023.04.18/boj7568/boj7568_pythonic.py
close #247 
일일 목표 달성
```python
import sys
size = [list(map(int, x.split())) for x in sys.stdin.read().splitlines()[1:]]
result = [1] * len(size)
for i, person in enumerate(size[:-1]):
for j, comparison in enumerate(size[i+1:]):
if person[0] > comparison[0] and person[1] > comparison[1]:
result[i + j + 1] += 1
elif person[0] < comparison[0] and person[1] < comparison[1]:
result[i] += 1
sys.stdout.write(' '.join(map(str, result)))
```
```python
import sys
size = [list(map(int, x.split())) for x in sys.stdin.read().splitlines()[1:]]
compare = [sum([person1[0] < person2[0] and person1[1] < person2[1] for person2 in size]) for person1 in size]
sys.stdout.write(' '.join([str(rank + 1) for rank in compare]))
```
pythonic한 방법의 코드를 일반적인 방법과 함께 고민해봤다. 리뷰어들은 어떤걸 선호하시나요?
> [python] #247 solve boj7568

- 김민재/week9/2023.04.28/boj10816/README.md
- 김민재/week9/2023.04.28/boj10816/boj10816.py
close #258 
일일 목표 달성
```python
import sys
from collections import Counter
cards, predictions = map(lambda x: map(int, x.split()), sys.stdin.read().splitlines()[1::2])
card_count = Counter(cards)
sys.stdout.write(' '.join(str(card_count[prediction]) for prediction in predictions))
```
python으로는 속도를 올리기 힘들어서 python보다 메모리를 많이 쓰지만, 속도가 빠른 PyPy3를 사용해보았다.
> [PyPy3] #258 solve boj10816

- 이건우/week7/README.md
- 이건우/week7/leetcode1480.py
#242 
주간 목표 달성
Given an array nums. We define a running sum of an array as runningSum[i] = sum(nums[0]…nums[i]).
Return the running sum of nums.
---
Constraints:
1 <= `nums.length` <= 1000
-10^6 <= `nums[i]` <= 10^6
```python
class Solution(object):
def runningSum(self, nums):
"""
:type nums: List[int]
:rtype: List[int]
"""
res = []
sums = 0
for _ in nums:
sums += _
res.append(sums)
return res
```
뭔가 더 간단한 방법이 있지 않을까 싶습니다 ..
> [python] #242 solve leetcode1480

- 김민재/week10/2023.05.01/boj10828/README.md
- 김민재/week10/2023.05.01/boj10828/boj10828.py
close #267 
일일 목표 달성
```python
import sys
inputs = sys.stdin.read().splitlines()[1:]
stack = []
result = []
for command in inputs:
if command.startswith("push"):
stack.append(command.split()[1])
elif command == "pop":
result.append(stack.pop() if stack else "-1")
elif command == "size":
result.append(str(len(stack)))
elif command == "empty":
result.append('0' if stack else '1')
elif command == "top":
result.append(stack[-1] if stack else "-1")
```
입출력을 이용해서 스택을 사용할 수 있게 만들어주는 간단한 문제다.
> [python] #267 solve boj10828

- 김민재/week10/2023.05.03/README.md
- 김민재/week10/2023.05.03/boj10845.py
close #268 
일일 목표 달성
```python
import sys
from collections import deque
inputs = sys.stdin.read().splitlines()[1:]
deq = deque()
result = []
for command in inputs:
if command.startswith("push"):
deq.append(command.split()[1])
elif command == "pop":
result.append(deq.popleft() if deq else "-1")
elif command == "size":
result.append(str(len(deq)))
elif command == "empty":
result.append("0" if deq else "1")
elif command == "front":
result.append(deq[0] if deq else "-1")
elif command == "back":
result.append(deq[-1] if deq else "-1")
```
#270 문제를 큐로 바꾼 버전이다. 다만 앞과 뒤로 접근해서 요소를 얻을 수 있어야 하기 때문에, queue 모듈을 쓰지 않았고, list 기반으로 pop(1)을 사용하는 방법은 o(n)의 시간복잡도가 걸리기 때문에, deque 모듈을 사용했다.
> [python] #268 solve boj10845

- 김민재/week11/2023.05.11/boj10989/README.md
- 김민재/week11/2023.05.11/boj10989/boj10989.py
close #277 
일일 목표 달성
```python
import sys
nums = [0] * 10000
for _ in range(int(sys.stdin.readline())):
nums[int(sys.stdin.readline()) - 1] += 1
for num, count in enumerate(nums):
for _ in range(count):
sys.stdout.write(str(num + 1) + '\n')
```
조금이라도 한번에 합쳐서 입출력을 진행하려고 하면 메모리 초과가 뜨기 때문에, 입출력 빈도를 최대한 줄이려고 하는 나로써는 불편한 문제였다.
최대한 메모리의 사용을 줄이는게 핵심인 문제.
언제나처럼 메모이제이션을 사용했다.
> [PyPy3] #277 solve boj10989

- 김민재/week10/2023.05.06/boj10866/README.md
- 김민재/week10/2023.05.06/boj10866/boj10866.py
close #269 
일일 목표 달성
```python
import sys
from collections import deque
inputs = sys.stdin.read().splitlines()[1:]
deq = deque()
result = []
for command in inputs:
if command.startswith("push_front"):
deq.appendleft(command.split()[1])
if command.startswith("push_back"):
deq.append(command.split()[1])
elif command == "pop_front":
result.append(deq.popleft() if deq else "-1")
elif command == "pop_back":
result.append(deq.pop() if deq else "-1")
elif command == "size":
result.append(str(len(deq)))
elif command == "empty":
result.append("0" if deq else "1")
elif command == "front":
result.append(deq[0] if deq else "-1")
elif command == "back":
result.append(deq[-1] if deq else "-1")
```
[맞았습니다!!](http://boj.kr/cc2fcd5a145040f595a4d81aaeaa09ea)
#271 에서 이미 …
> [python] #269 solve boj10866

- 김민재/week8/2023.04.20/boj9012/README.md
- 김민재/week8/2023.04.20/boj9012/boj9012.py
close #248 
일일 목표 달성
```python
import sys
inputs = sys.stdin.read().splitlines()[1:]
result = []
for line in inputs:
parenthesis_count = 0
for i, char in enumerate(line):
if char == '(':
parenthesis_count += 1
elif char == ')':
parenthesis_count -= 1
if len(line) - 1 - i < parenthesis_count or parenthesis_count < 0:
break
result.append("YES" if parenthesis_count == 0 else "NO")
```
얼마 전 풀었던 #244 의 하위호환 문제다. 원래는 stack을 사용하는 문제였겠지만, 조건도 단순하고 얼마 전 이보다 상위의 문제를 해결했기에 좀 다르게 카운팅을 통해서 해결해보았다.
> [python] #248 solve boj9012

- 김민재/week12/2023.05.19/boj11866/README.md
- 김민재/week12/2023.05.19/boj11866/boj11866.py
close #285 
일일 목표 달성
```python
import sys
N, K = map(int, sys.stdin.readline().split())
que = list(range(1, N + 1))
index = 0
result = []
while que:
index += K - 1
index %= len(que)
result.append(str(que.pop(index)))
sys.stdout.write('<' + ", ".join(result) + ">\n")
```
itertools circle을 활욜할 방법을 고민해봤는데 불필요하게 과한 구현이라 생각되어 포기했다. queue를 사용해서 구현했다가, 반복적으로 pop하는 작업에 시간이 많이 소요되어 리스트의 인덱스로 처리해주었다.
> [python] #285 solve boj11866

- 이건우/week10/README.md
- 이건우/week10/leetcod1342.py
- 이건우/week10/leetcode876.py
#272
주간 목표 달성
Given an integer num, return the number of steps to reduce it to zero.
In one step, if the current number is even, you have to divide it by 2, otherwise, you have to subtract 1 from it.
Example 1:
Input: num = 14
Output: 6
Explanation: 
Step 1) 14 is even; divide by 2 and obtain 7. 
Step 2) 7 is odd; subtract 1 and obtain 6.
Step 3) 6 is even; divide by 2 and obtain 3. 
Step 4) 3 is odd; subtract 1 and obtain 2. 
Step 5) 2 is even; divide by 2 and obtain 1. 
Step 6) 1 is odd; subtract 1 and obtain 0.
Example 2:
Input: num = 8
Output: 4
Explanation: 
Step 1) 8 is even; divide by 2 and obtain 4. 
Step 2) 4 is even; divide by 2 and obtain 2. 
Step 3) 2 is even; divide by 2 and obtain 1. 
Step 4) 1 is odd; subtract 1 and obtain 0.
Example 3:
Input: num = 123
Output: 12 …
> [python] #272 solve leetcode 1342, 876

- 김민재/week15/2023.05.19/boj15829/README.md
- 김민재/week15/2023.05.19/boj15829/boj15829.py
close #291 
일일 목표 달성
```python
import sys
L = int(sys.stdin.readline())
string = sys.stdin.readline().rstrip()
hash_result = sum((ord(char) - ord('a') + 1) * (31 ** i) for i, char in enumerate(string)) % 1234567891
sys.stdout.write(str(hash_result))
```
간단한 해시 함수 개념 문제
> [python] #291 solve boj15829

- 김민재/week9/2023.04.27/boj10814/README.md
- 김민재/week9/2023.04.27/boj10814/boj10814.py
close #257 
일일 목표 달성
```python
import sys
users = sys.stdin.read().splitlines()[1:]
users = sorted(users, key=lambda x: int(x.split()[0]))
sys.stdout.write('\n'.join(users))
```
정렬의 키값을 설정해서 정렬 하는 간단한 문제
> [python] #257 solve boj10814

- 김민재/week12/2023.05.15/boj11650/README.md
- 김민재/week12/2023.05.15/boj11650/boj11650.py
close #283 
일일 목표 달성
```python
import sys
inputs = sys.stdin.read().split()[1:]
pos = sorted(zip(inputs[::2], inputs[1::2]), key=lambda x: (int(x[0]), int(x[1])))
sys.stdout.write('\n'.join('{} {}'.format(*p) for p in pos))
```
다중 키를 이용한 정렬을 수행할 줄 아는지 물어보는 문제였다. 데이터의 전처리를 수행해서 최대한 깔끔하게 코드를 구성해보았다.
> [python] #283 solve boj11650

- 김민재/week16/2023.06.09/boj1074/README.md
- 김민재/week16/2023.06.09/boj1074/boj1074.py
close #300
일일 목표 달성
```python
import sys
N, r, c = map(int, sys.stdin.readline().split())
result = 0
for n in range(N, 0, -1):
split_point = 2 ** (n - 1)
if r >= split_point and c >= split_point:
result += 3 * (split_point ** 2)
r %= split_point
c %= split_point
elif r >= split_point:
result += 2 * (split_point ** 2)
r %= split_point
elif c >= split_point:
result += split_point ** 2
c %= split_point
sys.stdout.write(str(result))
```
브루투포스를 사용하면 탐색 횟수가 너무 많아진다. 시간복잡도를 O(logN)으로 낮추는것이 핵심.
> [python] #300 solve boj1074

- 김민재/week17/2023.06.16/boj1389/README.md
- 김민재/week17/2023.06.16/boj1389/boj1389.py
close #308 
일일 목표 달성
```python
import sys
N, M = map(int, sys.stdin.readline().split())
graph = [[float("inf")] * N for _ in range(N)]
for i in range(N):
graph[i][i] = 0
for _ in range(M):
i, j = map(lambda x: int(x) - 1, sys.stdin.readline().split())
graph[i][j] = graph[j][i] = 1
for k in range(N):
for i in range(N):
for j in range(N):
graph[i][j] = min(graph[i][j], graph[i][k] + graph[k][j])
sys.stdout.write(str(min(enumerate(graph), key=lambda x: sum(x[1]))[0] + 1))
```
플로이드–워셜 알고리즘 적용 과정에서 중간노드를 가장 안쪽 반복문에서 설정하는 바람에 몇번의 리트라이를 했다. :(
> [python] #308 solve boj1389

- 김민재/week17/2023.06.15/boj1260/README.md
- 김민재/week17/2023.06.15/boj1260/boj1260.py
close #307 
일일 목표 달성
```python
import sys
from collections import defaultdict
from collections import deque
def dfs(node):
dfs_visited[node] = True
visited_node = [node]
for path in sorted(graph[node]):
if not dfs_visited[path]:
visited_node += dfs(path)
return visited_node
def bfs(start):
bfs_visited[start] = True
que = deque([start])
visited_node = []
while que:
visited_node.append(que.popleft())
for node in sorted(graph[visited_node[-1]]):
if not bfs_visited[node]:
que.append(node)
bfs_visited[node] = True
return visited_node
N, M, V = map(int, sys.stdin.readline().split())
graph = defaultdict(set)
for _ in range(M):
s, e = map(int, sys.stdin.readline().split())
graph[s].add(e)
graph[e].add(s)
dfs_visited = [False] * (N + 1)
bfs_visited = [False] * (N + 1)
sys.stdout.write(' …
```
> [python] #307 solve boj1260

- 김민재/week17/2023.06.13/boj1107/README.md
- 김민재/week17/2023.06.13/boj1107/boj1107.py
close #305 
일일 목표 달성
```python
import sys
N = int(sys.stdin.readline())
M = int(sys.stdin.readline())
if M:
broken = sys.stdin.readline().split()
else:
broken = []
result = abs(100 - N)
for num in range(1000001):
for button in str(num):
if button in broken:
break
else:
result = min(result, len(str(num)) + abs(num - N))
sys.stdout.write(str(result))
```
분명히 DFS나 BFS를 이용해서 부서지지 않은 버튼들의 조합들을 만들어서 최소값을 구할 수 있는 문제인데 문제의 태그에 브루트포스만이 존재한다. 일단 태그를 존중해 브루트포스 알고리즘을 이용해 구현했다. 나중에 DFS로 구현해볼만한 문제.
> [python] #305 solve boj1107
